site_name: RDMA101
site_url: https://renfeng.org/RDMA101/
theme:
  name: material
nav:
  - 首页: index.md
  - 第一篇：快速入门: 01-introduction.md
  - 第二篇：编程模型: 02-programming-model.md
  - 第三篇：内部原理: 03-internals.md
  - 第四篇：优化技巧: 04-optimization.md
  - 第五篇：实例研究: 05-case-studies.md
